language: node_js
node_js:
  - "6.9.2"
  - "4.7.0"
  - "iojs"
sudo: false
before_install: npm install -g grunt-cli
cache:
  directories:
    - node_modules
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
